# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harmony-server

# >> macros
# << macros

Summary:    The harmony-server
Version:    0.0
Release:    1
Group:      Qt/Qt
License:    BSD
URL:        https://github.com/SfietKonstantin/harmony-server
Source0:    %{name}-%{version}.tar.bz2
Source100:  harmony-server.yaml
Requires:   nodejs
BuildRequires:  nodejs-npm
BuildRequires:  autoconf
BuildRequires:  automake

%description
An experiment about running a webapplication 
to expose phone information


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
./build.sh install
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_datadir}/%{name}
# >> files
# << files
